@ Generated by gcc 3.2.2 for StrongARM/WinCE/PE
	.file	"/src/pvis/3frac.c"
	.global	a
	.bss
	.align	0
a:
	.space	64
	.global	b
	.align	0
b:
	.space	64
	.global	gam
	.data
	.align	0
gam:
	.word	1717986918
	.word	1074161254
	.global	ob
	.bss
	.align	0
ob:
	.space	4
	.global	df
	.data
	.align	0
df:
	.word	2
	.align	0
_ZZ6PVTickdE2px:
	.word	0
	.align	0
_ZZ6PVTickdE2py:
	.word	0
	.align	0
_ZZ6PVTickdE2pz:
	.word	0
	.align	0
_ZZ6PVTickdE2dr:
	.word	0
	.align	0
_ZZ6PVTickdE3fov:
	.word	1110704128
	.text
	.align	0
	.global	_Z6PVTickd
_Z6PVTickd:
	@ args = 0, pretend = 0, frame = 104
	@ frame_needed = 1, uses_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #176
	sub	r2, fp, #48
	stmib	r2, {r0-r1}
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #32
	cmp	r3, #0
	beq	L2
	mov	r3, #512
	str	r3, [fp, #-120]
	b	L1
L2:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #1048576
	cmp	r3, #0
	beq	L3
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #16
	cmp	r3, #0
	beq	L3
	ldr	r3, L14+64
	ldr	r3, [r3, #0]
	cmp	r3, #0
	beq	L4
	ldr	r2, L14+64
	mov	r3, #0
	str	r3, [r2, #0]
	b	L3
L4:
	ldr	r2, L14+64
	mov	r3, #2
	str	r3, [r2, #0]
L3:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #4194304
	cmp	r3, #0
	beq	L6
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #64
	cmp	r3, #0
	beq	L6
	ldr	r3, L14+12
	ldr	r0, [r3, #0]	@ float
	ldr	r1, L14	@ float
	bl	__nesf2
	mov	r3, r0
	cmp	r3, #0
	bne	L9
	b	L7
L9:
	ldr	r2, L14	@ float
	str	r2, [fp, #-124]	@ float
	b	L8
L15:
	.align	0
L14:
	.word	1065353216
	.word	gam
	.word	PVInput
	.word	_ZZ6PVTickdE2dr
	.word	0
	.word	-1026555904
	.word	_ZZ6PVTickdE3fov
	.word	1123680256
	.word	1116995584
	.word	_ZZ6PVTickdE2pz
	.word	_ZZ6PVTickdE2px
	.word	_ZZ6PVTickdE2py
	.word	a
	.word	1061158912
	.word	ob
	.word	b
	.word	df
	.word	824633721
	.word	1065135112
	.word	-1717986918
	.word	1069128089
	.word	-1717986918
	.word	1070176665
	.word	0
	.word	1079574528
	.word	-1717986918
	.word	1068079513
	.word	-687194767
	.word	1072001187
L7:
	ldr	r3, L14+16	@ float
	str	r3, [fp, #-124]	@ float
L8:
	ldr	r3, [fp, #-124]	@ float
	ldr	r2, L14+12
	str	r3, [r2, #0]	@ float
L6:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #1
	and	r3, r3, #255
	cmp	r3, #0
	beq	L10
	ldr	r5, L14+24
	ldr	r3, L14+24
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	adr	r2, L14+68
	ldmia	r2, {r2-r3}
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	bl	__truncdfsf2
	mov	r3, r0
	str	r3, [r5, #0]	@ float
L10:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #2
	cmp	r3, #0
	beq	L11
	ldr	r5, L14+24
	ldr	r3, L14+24
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	adr	r2, L14+68
	ldmia	r2, {r2-r3}
	bl	__subdf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	bl	__truncdfsf2
	mov	r3, r0
	str	r3, [r5, #0]	@ float
L11:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #4
	cmp	r3, #0
	beq	L12
	ldr	r5, L14+4
	ldr	r3, L14+4
	ldmia	r3, {r0-r1}
	adr	r2, L14+76
	ldmia	r2, {r2-r3}
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	stmia	r5, {r3-r4}
	ldr	r3, L14+4
	ldmia	r3, {r0-r1}
	bl	_Z10PVSetGammad
L12:
	ldr	r3, L14+8
	ldr	r3, [r3, #12]
	and	r3, r3, #8
	cmp	r3, #0
	beq	L13
	ldr	r5, L14+4
	ldr	r3, L14+4
	ldmia	r3, {r0-r1}
	adr	r2, L14+76
	ldmia	r2, {r2-r3}
	bl	__subdf3
	mov	r4, r1
	mov	r3, r0
	stmia	r5, {r3-r4}
	ldr	r3, L14+4
	ldmia	r3, {r0-r1}
	bl	_Z10PVSetGammad
L13:
	ldr	r5, L14+40
	ldr	r3, L14+40
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r7, r1
	mov	r6, r0
	ldr	r3, L14+8
	ldrsh	r3, [r3, #6]
	mov	r0, r3
	bl	__floatsisf
	mov	r3, r0
	mov	r0, r3
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	adr	r2, L14+92
	ldmia	r2, {r2-r3}
	bl	__divdf3
	mov	r9, r1
	mov	r8, r0
	sub	r2, fp, #48
	ldmib	r2, {r0-r1}
	adr	r2, L14+84
	ldmia	r2, {r2-r3}
	bl	__muldf3
	sub	r3, fp, #128
	stmda	r3, {r0-r1}
	ldr	r3, L14+12
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	sub	r2, fp, #128
	ldmda	r2, {r0-r1}
	mov	r2, r3
	mov	r3, r4
	bl	__muldf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r9
	mov	r0, r8
	mov	r2, r3
	mov	r3, r4
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r7
	mov	r0, r6
	mov	r2, r3
	mov	r3, r4
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	bl	__truncdfsf2
	mov	r3, r0
	str	r3, [r5, #0]	@ float
	ldr	r5, L14+44
	ldr	r3, L14+44
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r7, r1
	mov	r6, r0
	ldr	r3, L14+8
	ldrsh	r3, [r3, #8]
	mov	r0, r3
	bl	__floatsisf
	mov	r3, r0
	mov	r0, r3
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	adr	r2, L14+92
	ldmia	r2, {r2-r3}
	bl	__divdf3
	mov	r9, r1
	mov	r8, r0
	sub	r3, fp, #48
	ldmib	r3, {r0-r1}
	adr	r2, L14+100
	ldmia	r2, {r2-r3}
	bl	__muldf3
	sub	r2, fp, #144
	stmib	r2, {r0-r1}
	ldr	r3, L14+12
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	sub	r2, fp, #144
	ldmib	r2, {r0-r1}
	mov	r2, r3
	mov	r3, r4
	bl	__muldf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r9
	mov	r0, r8
	mov	r2, r3
	mov	r3, r4
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r7
	mov	r0, r6
	mov	r2, r3
	mov	r3, r4
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	bl	__truncdfsf2
	mov	r3, r0
	str	r3, [r5, #0]	@ float
	ldr	r5, L14+36
	ldr	r3, L14+36
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r7, r1
	mov	r6, r0
	sub	r3, fp, #48
	ldmib	r3, {r0-r1}
	adr	r2, L14+108
	ldmia	r2, {r2-r3}
	bl	__muldf3
	mov	r9, r1
	mov	r8, r0
	ldr	r3, L14+12
	ldr	r0, [r3, #0]	@ float
	bl	__extendsfdf2
	mov	r4, r1
	mov	r3, r0
	mov	r1, r9
	mov	r0, r8
	mov	r2, r3
	mov	r3, r4
	bl	__muldf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r7
	mov	r0, r6
	mov	r2, r3
	mov	r3, r4
	bl	__adddf3
	mov	r4, r1
	mov	r3, r0
	mov	r1, r4
	mov	r0, r3
	bl	__truncdfsf2
	mov	r3, r0
	str	r3, [r5, #0]	@ float
	ldr	r0, L14+60
	bl	_Z15PVTLoadIdentityP9PVTMatrix
	ldr	r0, L14+48
	bl	_Z15PVTLoadIdentityP9PVTMatrix
	ldr	r0, L14+48
	ldr	r1, L14+16	@ float
	ldr	r2, L14+16	@ float
	ldr	r3, L14+20	@ float
	bl	_Z12PVTTranslateP9PVTMatrixfff
	ldr	r2, L14+24
	ldr	r3, L14+28	@ float
	str	r3, [sp, #0]	@ float
	ldr	r0, L14+48
	ldr	r1, [r2, #0]	@ float
	ldr	r2, L14+52	@ float
	ldr	r3, L14+32	@ float
	bl	_Z10PVTProjectP9PVTMatrixffff
	ldr	r3, L14+44
	ldr	r2, L14+40
	ldr	ip, L14+36
	ldr	r0, L14+60
	ldr	r1, [r3, #0]	@ float
	ldr	r2, [r2, #0]	@ float
	ldr	r3, [ip, #0]	@ float
	bl	_Z9PVTRotateP9PVTMatrixfff
	ldr	r3, L14+48
	sub	lr, fp, #112
	mov	ip, r3
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip, {r0, r1, r2, r3}
	stmia	lr, {r0, r1, r2, r3}
	ldr	r3, L14+60
	str	r3, [sp, #48]
	mov	lr, sp
	sub	ip, fp, #96
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip, {r0, r1, r2, r3}
	stmia	lr, {r0, r1, r2, r3}
	sub	r3, fp, #112
	ldmia	r3, {r0, r1, r2, r3}
	bl	_Z13PVTMultMatrix9PVTMatrixPS_
	sub	r3, fp, #116
	mov	r0, r3
	mov	r1, #0
	mov	r2, #0
	mov	r3, #0
	bl	_Z5PVrgbhhh
	ldr	r0, [fp, #-116]
	mov	r1, #0
	bl	_Z5PVcls7PVColorm
	ldr	r3, L14+56
	ldr	r3, [r3, #0]
	sub	lr, fp, #112
	mov	ip, r3
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldr	r3, [ip, #0]
	str	r3, [lr, #0]
	ldr	r3, L14+60
	add	lr, sp, #4
	mov	ip, r3
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip!, {r0, r1, r2, r3}
	stmia	lr!, {r0, r1, r2, r3}
	ldmia	ip, {r0, r1, r2, r3}
	stmia	lr, {r0, r1, r2, r3}
	ldr	r3, L14+64
	ldr	r3, [r3, #0]
	str	r3, [sp, #68]
	ldr	r3, [fp, #-96]
	str	r3, [sp, #0]
	sub	r3, fp, #112
	ldmia	r3, {r0, r1, r2, r3}
	bl	_Z10PVTDrawObj6PVTObj9PVTMatrixm
	mov	r2, #256
	str	r2, [fp, #-120]
L1:
	ldr	r0, [fp, #-120]
	ldmea	fp, {r4, r5, r6, r7, r8, r9, fp, sp, pc}
	.data
	.align	0
_ZZ6PVInitvE2os:
	.word	1065353216
	.word	0
	.word	0
	.word	-1082130432
	.word	0
	.word	0
	.word	0
	.word	1065353216
	.word	0
	.word	0
	.word	-1082130432
	.word	0
	.word	0
	.word	0
	.word	1065353216
	.word	0
	.word	0
	.word	-1082130432
	.section .rdata
	.align	0
LC0:
	.ascii	"Couldn't create object\000"
	.text
	.align	0
	.global	_Z6PVInitv
_Z6PVInitv:
	@ args = 0, pretend = 0, frame = 80
	@ frame_needed = 1, uses_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {r4, fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #80
	mov	r3, #3
	str	r3, [fp, #-24]
	mov	r3, #3
	str	r3, [fp, #-20]
L17:
	ldr	r3, [fp, #-20]
	sub	r3, r3, #1
	str	r3, [fp, #-20]
	cmn	r3, #1
	bne	L19
	b	L18
L19:
	ldr	r3, [fp, #-24]
	mov	r2, r3
	mov	r2, r2, asl #3
	rsb	r3, r3, r2
	str	r3, [fp, #-24]
	b	L17
L18:
	ldr	r3, [fp, #-24]
	mov	r3, r3, asl #1
	mov	r0, r3
	ldr	r1, [fp, #-24]
	bl	_Z12PVTCreateObjmm
	mov	r3, r0
	ldr	r2, L37
	str	r3, [r2, #0]
	ldr	r3, [r2, #0]
	cmp	r3, #0
	bne	L20
	ldr	r0, L37+4
	bl	_Z17PVSetErrorMessagePc
	mov	r3, #768
	str	r3, [fp, #-96]
	b	L16
L20:
	ldr	r3, L37
	ldr	r3, [r3, #0]
	ldr	r4, [r3, #8]
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+8	@ float
	ldr	r2, L37+12	@ float
	ldr	r3, L37+12	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #16
	ldr	r3, [r3, #8]
	add	r4, r2, r3
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+16	@ float
	ldr	r2, L37+12	@ float
	ldr	r3, L37+12	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #32
	ldr	r3, [r3, #8]
	add	r4, r2, r3
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+12	@ float
	ldr	r2, L37+8	@ float
	ldr	r3, L37+12	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #48
	ldr	r3, [r3, #8]
	add	r4, r2, r3
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+12	@ float
	ldr	r2, L37+16	@ float
	ldr	r3, L37+12	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #64
	ldr	r3, [r3, #8]
	add	r4, r2, r3
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+12	@ float
	ldr	r2, L37+12	@ float
	ldr	r3, L37+8	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #80
	ldr	r3, [r3, #8]
	add	r4, r2, r3
	sub	r3, fp, #80
	mov	r0, r3
	ldr	r1, L37+12	@ float
	ldr	r2, L37+12	@ float
	ldr	r3, L37+16	@ float
	bl	_Z6PVTxyzfff
	mov	ip, r4
	sub	r3, fp, #80
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	mov	r3, #0
	str	r3, [fp, #-20]
L21:
	ldr	r3, [fp, #-20]
	cmp	r3, #5
	bls	L24
	b	L22
L24:
	ldr	r3, L37
	ldr	r1, [r3, #0]
	ldr	r3, [fp, #-20]
	mov	r2, r3, asl #2
	ldr	r3, [r1, #12]
	add	r2, r2, r3
	ldr	r3, [fp, #-20]
	str	r3, [r2, #0]
	ldr	r3, [fp, #-20]
	add	r3, r3, #1
	str	r3, [fp, #-20]
	b	L21
L22:
	ldr	r3, L37
	ldr	r3, [r3, #0]
	ldr	r4, [r3, #16]
	sub	r3, fp, #84
	mov	r0, r3
	mov	r1, #255
	mov	r2, #255
	mov	r3, #255
	bl	_Z5PVrgbhhh
	ldr	r3, [fp, #-84]
	str	r3, [r4, #0]
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #4
	ldr	r3, [r3, #16]
	add	r4, r2, r3
	sub	r3, fp, #88
	mov	r0, r3
	mov	r1, #255
	mov	r2, #255
	mov	r3, #255
	bl	_Z5PVrgbhhh
	ldr	r3, [fp, #-88]
	str	r3, [r4, #0]
	ldr	r3, L37
	ldr	r3, [r3, #0]
	mov	r2, #8
	ldr	r3, [r3, #16]
	add	r4, r2, r3
	sub	r3, fp, #92
	mov	r0, r3
	mov	r1, #255
	mov	r2, #255
	mov	r3, #255
	bl	_Z5PVrgbhhh
	ldr	r3, [fp, #-92]
	str	r3, [r4, #0]
	ldr	r3, L37+20	@ float
	str	r3, [fp, #-48]	@ float
	mov	r3, #3
	str	r3, [fp, #-28]
	mov	r3, #6
	str	r3, [fp, #-36]
	mov	r3, #6
	str	r3, [fp, #-40]
	mov	r3, #3
	str	r3, [fp, #-44]
	mov	r3, #0
	str	r3, [fp, #-20]
L25:
	ldr	r3, [fp, #-20]
	cmp	r3, #2
	bls	L28
	b	L26
L28:
	mov	r3, #0
	str	r3, [fp, #-24]
L29:
	ldr	r3, [fp, #-24]
	cmp	r3, #5
	bls	L32
	b	L30
L32:
	mov	r3, #0
	str	r3, [fp, #-32]
L33:
	ldr	r2, [fp, #-32]
	ldr	r3, [fp, #-28]
	cmp	r2, r3
	bcc	L36
	b	L31
L36:
	ldr	r3, L37
	ldr	r1, [r3, #0]
	ldr	r3, [fp, #-32]
	mov	r2, r3, asl #5
	ldr	r3, [r1, #8]
	add	r3, r2, r3
	sub	ip, fp, #64
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r1, L37+24
	ldr	r2, [fp, #-24]
	mov	r3, r2
	mov	r3, r3, asl #1
	add	r3, r3, r2
	mov	r3, r3, asl #2
	add	r3, r3, r1
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-64]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-64]	@ float
	ldr	r2, L37+24
	ldr	r1, [fp, #-24]
	mov	r0, #4
	mov	r3, r1
	mov	r3, r3, asl #1
	add	r3, r3, r1
	mov	r3, r3, asl #2
	add	r3, r3, r2
	add	r3, r3, r0
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-60]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-60]	@ float
	ldr	r2, L37+24
	ldr	r1, [fp, #-24]
	mov	r0, #8
	mov	r3, r1
	mov	r3, r3, asl #1
	add	r3, r3, r1
	mov	r3, r3, asl #2
	add	r3, r3, r2
	add	r3, r3, r0
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-56]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-56]	@ float
	ldr	r3, L37
	ldr	r0, [r3, #0]
	sub	ip, fp, #36
	ldr	r2, [ip, #0]
	mov	r3, r2
	mov	r1, r3, asl #2
	ldr	r3, [r0, #12]
	add	r1, r1, r3
	ldr	r3, [fp, #-40]
	str	r3, [r1, #0]
	add	r2, r2, #1
	str	r2, [ip, #0]
	ldr	r3, L37
	ldr	r1, [r3, #0]
	sub	lr, fp, #40
	ldr	r4, [lr, #0]
	mov	r3, r4
	mov	r2, r3, asl #4
	ldr	r3, [r1, #8]
	add	r3, r2, r3
	mov	ip, r3
	sub	r3, fp, #64
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	add	r4, r4, #1
	str	r4, [lr, #0]
	ldr	r3, L37
	ldr	r1, [r3, #0]
	ldr	r3, [fp, #-32]
	mov	r0, #16
	mov	r2, r3, asl #5
	ldr	r3, [r1, #8]
	add	r3, r2, r3
	add	r3, r3, r0
	sub	ip, fp, #64
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	ldr	r1, L37+24
	ldr	r2, [fp, #-24]
	mov	r3, r2
	mov	r3, r3, asl #1
	add	r3, r3, r2
	mov	r3, r3, asl #2
	add	r3, r3, r1
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-64]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-64]	@ float
	ldr	r2, L37+24
	ldr	r1, [fp, #-24]
	mov	r0, #4
	mov	r3, r1
	mov	r3, r3, asl #1
	add	r3, r3, r1
	mov	r3, r3, asl #2
	add	r3, r3, r2
	add	r3, r3, r0
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-60]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-60]	@ float
	ldr	r2, L37+24
	ldr	r1, [fp, #-24]
	mov	r0, #8
	mov	r3, r1
	mov	r3, r3, asl #1
	add	r3, r3, r1
	mov	r3, r3, asl #2
	add	r3, r3, r2
	add	r3, r3, r0
	ldr	r0, [r3, #0]	@ float
	ldr	r1, [fp, #-48]	@ float
	bl	__mulsf3
	mov	r3, r0
	ldr	r0, [fp, #-56]	@ float
	mov	r1, r3
	bl	__addsf3
	mov	r3, r0
	str	r3, [fp, #-56]	@ float
	ldr	r3, L37
	ldr	r0, [r3, #0]
	sub	ip, fp, #36
	ldr	r2, [ip, #0]
	mov	r3, r2
	mov	r1, r3, asl #2
	ldr	r3, [r0, #12]
	add	r1, r1, r3
	ldr	r3, [fp, #-40]
	str	r3, [r1, #0]
	add	r2, r2, #1
	str	r2, [ip, #0]
	ldr	r3, L37
	ldr	r1, [r3, #0]
	sub	lr, fp, #40
	ldr	r4, [lr, #0]
	mov	r3, r4
	mov	r2, r3, asl #4
	ldr	r3, [r1, #8]
	add	r3, r2, r3
	mov	ip, r3
	sub	r3, fp, #64
	ldmia	r3, {r0, r1, r2, r3}
	stmia	ip, {r0, r1, r2, r3}
	add	r4, r4, #1
	str	r4, [lr, #0]
	ldr	r3, L37
	ldr	r1, [r3, #0]
	sub	r0, fp, #44
	ldr	ip, [r0, #0]
	mov	r3, ip
	mov	r2, r3, asl #2
	ldr	r3, [r1, #16]
	add	r1, r2, r3
	ldr	r3, L37
	ldr	lr, [r3, #0]
	ldr	r3, [fp, #-32]
	mov	r2, r3, asl #2
	ldr	r3, [lr, #16]
	add	r3, r2, r3
	ldr	r3, [r3, #0]
	str	r3, [r1, #0]
	add	ip, ip, #1
	str	ip, [r0, #0]
	ldr	r3, [fp, #-32]
	add	r3, r3, #1
	str	r3, [fp, #-32]
	b	L33
L31:
	ldr	r3, [fp, #-24]
	add	r3, r3, #1
	str	r3, [fp, #-24]
	b	L29
L30:
	ldr	r0, [fp, #-48]	@ float
	ldr	r1, L37+28	@ float
	bl	__mulsf3
	mov	r3, r0
	str	r3, [fp, #-48]	@ float
	ldr	r2, [fp, #-28]
	mov	r3, r2
	mov	r3, r3, asl #3
	rsb	r3, r2, r3
	str	r3, [fp, #-28]
	ldr	r3, [fp, #-20]
	add	r3, r3, #1
	str	r3, [fp, #-20]
	b	L25
L26:
	mov	r3, #256
	str	r3, [fp, #-96]
L16:
	ldr	r0, [fp, #-96]
	ldmea	fp, {r4, fp, sp, pc}
L38:
	.align	0
L37:
	.word	ob
	.word	LC0
	.word	-1082130432
	.word	0
	.word	1065353216
	.word	1073741824
	.word	_ZZ6PVInitvE2os
	.word	1077936128
	.align	0
	.global	_Z7PVClosev
_Z7PVClosev:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	ldr	r3, L40
	ldr	r0, [r3, #0]
	bl	_Z13PVTDestroyObjP6PVTObj
	ldmea	fp, {fp, sp, pc}
L41:
	.align	0
L40:
	.word	ob
